### ISSUE TITLE
[Improve]: サンプル集ディレクトリを作成してサンプル実装をそこに集約する

### ISSUE THREAD

**Issue by blendthink** [yumemi-inc/flutter-mobile-project-template#275]
## 概要

- samples/github_app ディレクトリを作成して、そこに GitHub のリポジトリ一覧を表示・一覧のアイテムをタップしたら詳細を表示するようなサンプルアプリを新規作成する。
  - ランチャーアイコン・環境分けとかの対応は一切不要
  - ボトムタブやアプリバーも不要
  - go_router もいらないかも
  - hero アニメーションはいったん不要（別プルリクエストで対応したい）
- packages/samples ディレクトリを作成する
  - ここに features_github_repository パッケージを移動してパッケージ名を samples_github_repository に変更する
  - cores/core pagination 機能はパッケージとして切り出して、 packages/samples/pagination にパッケージを作成したいが、別プルリクエストで対応する
- 現状の apps/app の GitHub 関連の機能は削除して、画面の中央に Home というテキストを配置するだけにする
- ラベル機能は残しておいて、テンプレート機能を使った際のクリーンアップワークフローのときに samples 配下のものと packages/samples 配下のものを全て削除するようにする。クリーンアップワークフローで `melos bs` コマンドを実行してからコミットするように修正する

## 備考

- 今後、samples 配下のサンプル実装アプリは増えていく予定

## Tasks
- [x] packages/samples ディレクトリを作成して features_github_repository パッケージを移動
- [x] samples/github_app パッケージを作成
- [x] samples/github_app の GitHub 関連処理を追加
- [x] apps/app から samples_github_repository への依存を削除
- [ ] クリーンアップワークフローの調整

**Comment by tatsutakein** [comment]
ディレクトリは samples/github_app で作成する。
現在の apps/app は Use Template したときに、なにか削除等しなくても進められるような構成にする。

**Comment by tatsutakein** [comment]
わたしに割り当て済みだった Issue の PR が作成できたため、こちらに着手いたします 🙋
